package classifier

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/brianvoe/gofakeit/v7"
	"github.com/lucasschilin/s5n/advisor/internal/domain"
)

type StubAdapter struct{}

func NewStubAdapter() *StubAdapter {
	return &StubAdapter{}
}

func (s *StubAdapter) ClassifyIntent(
	ctx context.Context, userText, fallbackMessageQueueName string,
) (*domain.ClassifiedIntent, error) {

	// Normalize and extract the first word (lowercased)
	fields := strings.Fields(strings.ToUpper(userText))
	firstWord := ""
	if len(fields) > 0 {
		firstWord = fields[0]
	}

	fmt.Printf("FirstWord = %s\n", firstWord)

	switch firstWord {
	case "CREATE_REMINDER":
		// Generate fake data tailored for a reminder intent
		reminderDate := gofakeit.DateRange(
			time.Now().AddDate(0, 0, 1),
			time.Now().AddDate(0, 0, 30),
		)

		return &domain.ClassifiedIntent{
			TargetQueue: "reminder_agent",
			Action:      "CREATE_REMINDER",
			Confidence:  1.0,
			Parameters:  []byte(fmt.Sprintf(`{"title": "Fake reminder title - %s %d", "scheduled_at": "%s"}`, gofakeit.Word(), gofakeit.Number(1, 20), reminderDate.Format(time.RFC3339))),
		}, nil

	case "FALLBACK":
		return &domain.ClassifiedIntent{
			TargetQueue: fallbackMessageQueueName,
			Action:      "SEND_MESSAGE",
			Confidence:  1.0,
			Parameters:  []byte(`{"message": "Hello! Fallback message generated by StubAdapter"}`),
		}, nil

	default:
		// Default fallback strategy when the input doesn't start with a target keyword
		return &domain.ClassifiedIntent{
			TargetQueue: fallbackMessageQueueName,
			Action:      "SEND_MESSAGE",
			Confidence:  1.0,
			Parameters:  []byte(`{"message": "Hello! I don't understand your message, but here is a fallback response generated by StubAdapter"}`),
		}, nil
	}
}
